# 项目配置: 名称、日志目录
project:
  name: easy-admin
  log-directory: ${localPath:/home}/logs/easy_admin/${project.name}/${spring.profiles.active}

# 项目端口和url根路径
server:
  port: 1024
  servlet:
    context-path: /

# 环境
spring:
  profiles:
    active: '@profiles.active@'
